### ISSUE TITLE
Add following packages to namesubuntu

### ISSUE THREAD

**Issue by toddy** [PhillipSz/translationcheck#4]
ubuntu-filemanager-app
libqtelegram
ubuntu-terminal-app
indicator-bluetooth
indicator-transfer
indicator-sound
indicator-datetime
ubuntu-keyboard
location-service
ciborium
today-scope
ubuntu-ui-toolkit

And maybe software-center-agent -> but there I don't know if this are for Ubuntu Touch

**Comment by PhillipSz** [comment]
I can not add indicator-transfer, indicator-sound, indicator-datetime because it's already in https://translations.launchpad.net/ubuntu/wily/+lang/de/+index?batch=300
